app = "pet-mgt-api"
primary_region = "sin"

[build]
builder = "paketobuildpacks/builder-jammy-base"

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "requests"
hard_limit = 25
soft_limit = 20

[[http_service.checks]]
interval = "15s"
timeout = "2s"
method = "GET"
path = "/ping"

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
